### ISSUE TITLE
No Metadata of processed images

### ISSUE THREAD

**Issue by MelinaFr** [s-du/IRMapper#5]
Hi! Thanks for that software, it is pretty cool!
I'm still facing issues when trying to save the processed thermal images, all metadata get lost. 
Do you face the same issue?
Greetings
Melina

**Comment by s-du** [comment]
Hi Melina, thank you for your comment! I will have a look to this issue next week. It shouldn’t be to difficult to resolve. Kind regards

**Comment by s-du** [comment]
The new release should solve this issue!
